# ----------------------------------------------------------------------------
#
# Package             : promise
# Source Repo         : https://github.com/then/promise
# Travis Job Link     : https://travis-ci.com/github/santosh653/promise
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: node_js
sudo: false

node_js:
  - "10"
  - "12"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls
